// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ai.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAIDecision = `-- name: InsertAIDecision :one
INSERT INTO ai_decisions (request_id, recommendation, risk_score, confidence, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, request_id, recommendation, risk_score, confidence, reason, created_at
`

type InsertAIDecisionParams struct {
	RequestID      pgtype.UUID `json:"request_id"`
	Recommendation string      `json:"recommendation"`
	RiskScore      float64     `json:"risk_score"`
	Confidence     float64     `json:"confidence"`
	Reason         pgtype.Text `json:"reason"`
}

func (q *Queries) InsertAIDecision(ctx context.Context, arg InsertAIDecisionParams) (AiDecision, error) {
	row := q.db.QueryRow(ctx, insertAIDecision,
		arg.RequestID,
		arg.Recommendation,
		arg.RiskScore,
		arg.Confidence,
		arg.Reason,
	)
	var i AiDecision
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Recommendation,
		&i.RiskScore,
		&i.Confidence,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listAIDecisionsByRequest = `-- name: ListAIDecisionsByRequest :many
SELECT id, request_id, recommendation, risk_score, confidence, reason, created_at
FROM ai_decisions
WHERE request_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAIDecisionsByRequest(ctx context.Context, requestID pgtype.UUID) ([]AiDecision, error) {
	rows, err := q.db.Query(ctx, listAIDecisionsByRequest, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiDecision{}
	for rows.Next() {
		var i AiDecision
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Recommendation,
			&i.RiskScore,
			&i.Confidence,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
