// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: approvals.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelAllPendingApprovalsExcept = `-- name: CancelAllPendingApprovalsExcept :exec
UPDATE approvals
SET status = 'cancelled',
    decision_at = COALESCE(decision_at, NOW())
WHERE request_id = $1
  AND status = 'pending'
  AND id <> $2
`

type CancelAllPendingApprovalsExceptParams struct {
	RequestID pgtype.UUID `json:"request_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) CancelAllPendingApprovalsExcept(ctx context.Context, arg CancelAllPendingApprovalsExceptParams) error {
	_, err := q.db.Exec(ctx, cancelAllPendingApprovalsExcept, arg.RequestID, arg.ID)
	return err
}

const cancelAllPendingApprovalsForRequest = `-- name: CancelAllPendingApprovalsForRequest :exec
UPDATE approvals
SET status = 'cancelled',
    decision_at = NOW()
WHERE request_id = $1
  AND status = 'pending'
`

func (q *Queries) CancelAllPendingApprovalsForRequest(ctx context.Context, requestID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelAllPendingApprovalsForRequest, requestID)
	return err
}

const countPendingApprovalsForRequest = `-- name: CountPendingApprovalsForRequest :one
SELECT COUNT(*)::bigint
FROM approvals
WHERE request_id = $1
  AND status = 'pending'
`

func (q *Queries) CountPendingApprovalsForRequest(ctx context.Context, requestID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingApprovalsForRequest, requestID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const delegateApproval = `-- name: DelegateApproval :exec
UPDATE approvals AS ap
SET approver_id = $3,
    comment = COALESCE($4, ap.comment)
WHERE ap.id = $1
  AND ap.status = 'pending'
  AND (
    ap.approver_id = $2
    OR EXISTS (
      SELECT 1
      FROM delegations d
      WHERE d.from_user_id = ap.approver_id
        AND d.to_user_id = $2
        AND (
          d.permanent
          OR (
            d.start_date IS NOT NULL
            AND d.end_date IS NOT NULL
            AND CURRENT_DATE BETWEEN d.start_date AND d.end_date
          )
        )
        AND (
          NOT EXISTS (SELECT 1 FROM delegation_scopes ds0 WHERE ds0.delegation_id = d.id)
          OR EXISTS (
            SELECT 1
            FROM request_items ri
            INNER JOIN delegation_scopes ds ON ds.delegation_id = d.id AND ds.access_role_id = ri.access_role_id
            WHERE ri.request_id = ap.request_id
          )
        )
    )
  )
`

type DelegateApprovalParams struct {
	ID           pgtype.UUID `json:"id"`
	ApproverID   pgtype.UUID `json:"approver_id"`
	ApproverID_2 pgtype.UUID `json:"approver_id_2"`
	Comment      pgtype.Text `json:"comment"`
}

func (q *Queries) DelegateApproval(ctx context.Context, arg DelegateApprovalParams) error {
	_, err := q.db.Exec(ctx, delegateApproval,
		arg.ID,
		arg.ApproverID,
		arg.ApproverID_2,
		arg.Comment,
	)
	return err
}

const getPendingApprovalForRequestByApprover = `-- name: GetPendingApprovalForRequestByApprover :one
SELECT a.id, a.request_id, a.approver_id, a.step_number, a.status, a.decision_at, a.comment
FROM approvals a
WHERE a.request_id = $1
  AND a.status = 'pending'
  AND NOT EXISTS (
    SELECT 1
    FROM approvals p
    WHERE p.request_id = a.request_id
      AND p.status = 'pending'
      AND p.step_number < a.step_number
  )
  AND (
    a.approver_id = $2
    OR EXISTS (
      SELECT 1
      FROM delegations d
      WHERE d.from_user_id = a.approver_id
        AND d.to_user_id = $2
        AND (
          d.permanent
          OR (
            d.start_date IS NOT NULL
            AND d.end_date IS NOT NULL
            AND CURRENT_DATE BETWEEN d.start_date AND d.end_date
          )
        )
        AND (
          NOT EXISTS (SELECT 1 FROM delegation_scopes ds0 WHERE ds0.delegation_id = d.id)
          OR EXISTS (
            SELECT 1
            FROM request_items ri
            INNER JOIN delegation_scopes ds ON ds.delegation_id = d.id AND ds.access_role_id = ri.access_role_id
            WHERE ri.request_id = a.request_id
          )
        )
    )
  )
ORDER BY a.step_number ASC, a.id ASC
LIMIT 1
`

type GetPendingApprovalForRequestByApproverParams struct {
	RequestID  pgtype.UUID `json:"request_id"`
	ApproverID pgtype.UUID `json:"approver_id"`
}

func (q *Queries) GetPendingApprovalForRequestByApprover(ctx context.Context, arg GetPendingApprovalForRequestByApproverParams) (Approval, error) {
	row := q.db.QueryRow(ctx, getPendingApprovalForRequestByApprover, arg.RequestID, arg.ApproverID)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ApproverID,
		&i.StepNumber,
		&i.Status,
		&i.DecisionAt,
		&i.Comment,
	)
	return i, err
}

const inboxForApprover = `-- name: InboxForApprover :many
SELECT sub.id, sub.initiator_id, sub.status, sub.risk_score, sub.created_at, sub.updated_at, sub.justification,
       sub.needed_until, sub.step_number, sub.access_role_names,
       sub.initiator_full_name, sub.initiator_login
FROM (
  SELECT DISTINCT ON (r.id)
    r.id, r.initiator_id, r.status, r.risk_score, r.created_at, r.updated_at, r.justification,
    r.needed_until, a.step_number,
    COALESCE((
      SELECT string_agg(subq.role_name, ', ' ORDER BY subq.role_name)
      FROM (
        SELECT DISTINCT ar2.name AS role_name
        FROM request_items ri2
        INNER JOIN access_roles ar2 ON ar2.id = ri2.access_role_id
        WHERE ri2.request_id = r.id
      ) AS subq
    ), '')::text AS access_role_names,
    COALESCE(iu.full_name, '')::text AS initiator_full_name,
    COALESCE(iu.login, '')::text AS initiator_login
  FROM requests r
  INNER JOIN users iu ON iu.id = r.initiator_id
  INNER JOIN approvals a ON a.request_id = r.id
  WHERE a.status = 'pending'
    AND r.status = 'pending'
    AND NOT EXISTS (
      SELECT 1
      FROM approvals p
      WHERE p.request_id = r.id
        AND p.status = 'pending'
        AND p.step_number < a.step_number
    )
    AND (
      a.approver_id = $1
      OR EXISTS (
        SELECT 1
        FROM delegations d
        WHERE d.from_user_id = a.approver_id
          AND d.to_user_id = $1
          AND (
            d.permanent
            OR (
              d.start_date IS NOT NULL
              AND d.end_date IS NOT NULL
              AND CURRENT_DATE BETWEEN d.start_date AND d.end_date
            )
          )
          AND (
            NOT EXISTS (SELECT 1 FROM delegation_scopes ds0 WHERE ds0.delegation_id = d.id)
            OR EXISTS (
              SELECT 1
              FROM request_items ri
              INNER JOIN delegation_scopes ds ON ds.delegation_id = d.id AND ds.access_role_id = ri.access_role_id
              WHERE ri.request_id = r.id
            )
          )
      )
    )
  ORDER BY r.id, a.step_number, a.id
) sub
ORDER BY sub.created_at DESC
`

// InboxForApproverRow — заявка во входящих с номером текущего шага согласования.
type InboxForApproverRow struct {
	ID                  pgtype.UUID        `json:"id"`
	InitiatorID         pgtype.UUID        `json:"initiator_id"`
	Status              string             `json:"status"`
	RiskScore           pgtype.Float8      `json:"risk_score"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Justification       pgtype.Text        `json:"justification"`
	NeededUntil         pgtype.Date        `json:"needed_until"`
	StepNumber          int32              `json:"step_number"`
	AccessRoleNames     string             `json:"access_role_names"`
	InitiatorFullName   string             `json:"initiator_full_name"`
	InitiatorLogin      string             `json:"initiator_login"`
}

func (q *Queries) InboxForApprover(ctx context.Context, approverID pgtype.UUID) ([]InboxForApproverRow, error) {
	rows, err := q.db.Query(ctx, inboxForApprover, approverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxForApproverRow{}
	for rows.Next() {
		var i InboxForApproverRow
		if err := rows.Scan(
			&i.ID,
			&i.InitiatorID,
			&i.Status,
			&i.RiskScore,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Justification,
			&i.NeededUntil,
			&i.StepNumber,
			&i.AccessRoleNames,
			&i.InitiatorFullName,
			&i.InitiatorLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertApproval = `-- name: InsertApproval :exec
INSERT INTO approvals (id, request_id, approver_id, step_number, status)
VALUES ($1, $2, $3, $4, $5)
`

type InsertApprovalParams struct {
	ID         pgtype.UUID `json:"id"`
	RequestID  pgtype.UUID `json:"request_id"`
	ApproverID pgtype.UUID `json:"approver_id"`
	StepNumber int32       `json:"step_number"`
	Status     string      `json:"status"`
}

func (q *Queries) InsertApproval(ctx context.Context, arg InsertApprovalParams) error {
	_, err := q.db.Exec(ctx, insertApproval,
		arg.ID,
		arg.RequestID,
		arg.ApproverID,
		arg.StepNumber,
		arg.Status,
	)
	return err
}

const listApprovalsByRequest = `-- name: ListApprovalsByRequest :many
SELECT id, request_id, approver_id, step_number, status, decision_at, comment
FROM approvals
WHERE request_id = $1
ORDER BY step_number
`

func (q *Queries) ListApprovalsByRequest(ctx context.Context, requestID pgtype.UUID) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listApprovalsByRequest, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ApproverID,
			&i.StepNumber,
			&i.Status,
			&i.DecisionAt,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovalsByRequestWithUsers = `-- name: ListApprovalsByRequestWithUsers :many
SELECT
    a.id,
    a.request_id,
    a.approver_id,
    a.step_number,
    a.status,
    a.decision_at,
    a.comment,
    COALESCE(u.full_name, '')::text AS approver_full_name,
    u.login AS approver_login
FROM approvals a
LEFT JOIN users u ON u.id = a.approver_id
WHERE a.request_id = $1
ORDER BY a.step_number
`

type ListApprovalsByRequestWithUsersRow struct {
	ID               pgtype.UUID        `json:"id"`
	RequestID        pgtype.UUID        `json:"request_id"`
	ApproverID       pgtype.UUID        `json:"approver_id"`
	StepNumber       int32              `json:"step_number"`
	Status           string             `json:"status"`
	DecisionAt       pgtype.Timestamptz `json:"decision_at"`
	Comment          pgtype.Text        `json:"comment"`
	ApproverFullName string             `json:"approver_full_name"`
	ApproverLogin    pgtype.Text        `json:"approver_login"`
}

func (q *Queries) ListApprovalsByRequestWithUsers(ctx context.Context, requestID pgtype.UUID) ([]ListApprovalsByRequestWithUsersRow, error) {
	rows, err := q.db.Query(ctx, listApprovalsByRequestWithUsers, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovalsByRequestWithUsersRow{}
	for rows.Next() {
		var i ListApprovalsByRequestWithUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ApproverID,
			&i.StepNumber,
			&i.Status,
			&i.DecisionAt,
			&i.Comment,
			&i.ApproverFullName,
			&i.ApproverLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApprovalByID = `-- name: UpdateApprovalByID :exec
UPDATE approvals
SET status = $2,
    decision_at = NOW(),
    comment = $3
WHERE id = $1
  AND status = 'pending'
`

type UpdateApprovalByIDParams struct {
	ID      pgtype.UUID `json:"id"`
	Status  string      `json:"status"`
	Comment pgtype.Text `json:"comment"`
}

func (q *Queries) UpdateApprovalByID(ctx context.Context, arg UpdateApprovalByIDParams) error {
	_, err := q.db.Exec(ctx, updateApprovalByID, arg.ID, arg.Status, arg.Comment)
	return err
}
