// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: attachments.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, user_id, request_id, original_name, content_type, s3_key, size_bytes, created_at
FROM attachments
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAttachmentByID(ctx context.Context, id pgtype.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestID,
		&i.OriginalName,
		&i.ContentType,
		&i.S3Key,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const insertAttachment = `-- name: InsertAttachment :one
INSERT INTO attachments (user_id, request_id, original_name, content_type, s3_key, size_bytes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, request_id, original_name, content_type, s3_key, size_bytes, created_at
`

type InsertAttachmentParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	RequestID    pgtype.UUID `json:"request_id"`
	OriginalName string      `json:"original_name"`
	ContentType  string      `json:"content_type"`
	S3Key        string      `json:"s3_key"`
	SizeBytes    int64       `json:"size_bytes"`
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, insertAttachment,
		arg.UserID,
		arg.RequestID,
		arg.OriginalName,
		arg.ContentType,
		arg.S3Key,
		arg.SizeBytes,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestID,
		&i.OriginalName,
		&i.ContentType,
		&i.S3Key,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByRequest = `-- name: ListAttachmentsByRequest :many
SELECT id, user_id, request_id, original_name, content_type, s3_key, size_bytes, created_at
FROM attachments
WHERE request_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAttachmentsByRequest(ctx context.Context, requestID pgtype.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByRequest, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequestID,
			&i.OriginalName,
			&i.ContentType,
			&i.S3Key,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
