// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
//   source: audit.sql (extended ListAuditLogs with filters)

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (id, user_id, request_id, action, details)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	ID        pgtype.UUID `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	RequestID pgtype.UUID `json:"request_id"`
	Action    string      `json:"action"`
	Details   []byte      `json:"details"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.UserID,
		arg.RequestID,
		arg.Action,
		arg.Details,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.user_id, a.request_id, a.action, a.details, a.created_at,
  COALESCE(u.login, '') AS user_login
FROM audit_logs a
LEFT JOIN users u ON u.id = a.user_id
WHERE
  ($3 = '' OR a.action ILIKE '%' || $3 || '%' OR COALESCE(a.details::text, '') ILIKE '%' || $3 || '%')
  AND ($4 = '00000000-0000-0000-0000-000000000000'::uuid OR a.user_id = $4)
  AND ($5 = '00000000-0000-0000-0000-000000000000'::uuid OR a.request_id = $5)
ORDER BY a.created_at DESC
LIMIT $1 OFFSET $2
`

// AuditLogListRow — запись журнала с логином пользователя для API.
type AuditLogListRow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	RequestID   pgtype.UUID        `json:"request_id"`
	Action      string             `json:"action"`
	Details     []byte             `json:"details"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UserLogin   string             `json:"user_login"`
}

type ListAuditLogsParams struct {
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
	Search          string      `json:"search"`
	FilterUserID    pgtype.UUID `json:"filter_user_id"`
	FilterRequestID pgtype.UUID `json:"filter_request_id"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLogListRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.FilterUserID,
		arg.FilterRequestID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLogListRow{}
	for rows.Next() {
		var i AuditLogListRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RequestID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
			&i.UserLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
