// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: catalog.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccessRoleByID = `-- name: GetAccessRoleByID :one
SELECT id, resource_id, name, description, risk_level
FROM access_roles
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAccessRoleByID(ctx context.Context, id pgtype.UUID) (AccessRole, error) {
	row := q.db.QueryRow(ctx, getAccessRoleByID, id)
	var i AccessRole
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.Name,
		&i.Description,
		&i.RiskLevel,
	)
	return i, err
}

const getAccessRoleDetail = `-- name: GetAccessRoleDetail :one
SELECT
    ar.id AS access_role_id,
    ar.resource_id,
    ar.name AS role_name,
    ar.description AS role_description,
    ar.risk_level,
    r.name AS resource_name,
    r.sensitive AS resource_sensitive,
    s.id AS system_id,
    s.name AS system_name
FROM access_roles ar
INNER JOIN resources r ON r.id = ar.resource_id
INNER JOIN systems s ON s.id = r.system_id
WHERE ar.id = $1
LIMIT 1
`

type GetAccessRoleDetailRow struct {
	AccessRoleID      pgtype.UUID `json:"access_role_id"`
	ResourceID        pgtype.UUID `json:"resource_id"`
	RoleName          string      `json:"role_name"`
	RoleDescription   pgtype.Text `json:"role_description"`
	RiskLevel         string      `json:"risk_level"`
	ResourceName      string      `json:"resource_name"`
	ResourceSensitive bool        `json:"resource_sensitive"`
	SystemID          pgtype.UUID `json:"system_id"`
	SystemName        string      `json:"system_name"`
}

func (q *Queries) GetAccessRoleDetail(ctx context.Context, id pgtype.UUID) (GetAccessRoleDetailRow, error) {
	row := q.db.QueryRow(ctx, getAccessRoleDetail, id)
	var i GetAccessRoleDetailRow
	err := row.Scan(
		&i.AccessRoleID,
		&i.ResourceID,
		&i.RoleName,
		&i.RoleDescription,
		&i.RiskLevel,
		&i.ResourceName,
		&i.ResourceSensitive,
		&i.SystemID,
		&i.SystemName,
	)
	return i, err
}

const listAccessRolesByResource = `-- name: ListAccessRolesByResource :many
SELECT id, resource_id, name, description, risk_level
FROM access_roles
WHERE resource_id = $1
ORDER BY name
`

func (q *Queries) ListAccessRolesByResource(ctx context.Context, resourceID pgtype.UUID) ([]AccessRole, error) {
	rows, err := q.db.Query(ctx, listAccessRolesByResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessRole{}
	for rows.Next() {
		var i AccessRole
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Name,
			&i.Description,
			&i.RiskLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesBySystem = `-- name: ListResourcesBySystem :many
SELECT id, system_id, name, description, owner_id, sensitive
FROM resources
WHERE system_id = $1
ORDER BY name
`

func (q *Queries) ListResourcesBySystem(ctx context.Context, systemID pgtype.UUID) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesBySystem, systemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.SystemID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.Sensitive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystems = `-- name: ListSystems :many
SELECT id, name, description
FROM systems
ORDER BY name
`

func (q *Queries) ListSystems(ctx context.Context) ([]System, error) {
	rows, err := q.db.Query(ctx, listSystems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []System{}
	for rows.Next() {
		var i System
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalogFlat = `-- name: ListCatalogFlat :many
SELECT
    s.id AS system_id,
    s.name AS system_name,
    s.description AS system_description,
    r.id AS resource_id,
    r.name AS resource_name,
    r.sensitive AS resource_sensitive,
    ar.id AS access_role_id,
    ar.name AS role_name,
    ar.description AS role_description,
    ar.risk_level
FROM systems s
INNER JOIN resources r ON r.system_id = s.id
INNER JOIN access_roles ar ON ar.resource_id = r.id
ORDER BY LOWER(s.name), LOWER(r.name), LOWER(ar.name)
`

type ListCatalogFlatRow struct {
	SystemID          pgtype.UUID `json:"system_id"`
	SystemName        string      `json:"system_name"`
	SystemDescription pgtype.Text `json:"system_description"`
	ResourceID        pgtype.UUID `json:"resource_id"`
	ResourceName      string      `json:"resource_name"`
	ResourceSensitive bool        `json:"resource_sensitive"`
	AccessRoleID      pgtype.UUID `json:"access_role_id"`
	RoleName          string      `json:"role_name"`
	RoleDescription   pgtype.Text `json:"role_description"`
	RiskLevel         string      `json:"risk_level"`
}

func (q *Queries) ListCatalogFlat(ctx context.Context) ([]ListCatalogFlatRow, error) {
	rows, err := q.db.Query(ctx, listCatalogFlat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCatalogFlatRow{}
	for rows.Next() {
		var i ListCatalogFlatRow
		if err := rows.Scan(
			&i.SystemID,
			&i.SystemName,
			&i.SystemDescription,
			&i.ResourceID,
			&i.ResourceName,
			&i.ResourceSensitive,
			&i.AccessRoleID,
			&i.RoleName,
			&i.RoleDescription,
			&i.RiskLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAccessRoles = `-- name: SearchAccessRoles :many
SELECT
    ar.id AS access_role_id,
    ar.resource_id,
    ar.name AS role_name,
    ar.description AS role_description,
    ar.risk_level,
    r.name AS resource_name,
    r.sensitive AS resource_sensitive,
    s.id AS system_id,
    s.name AS system_name
FROM access_roles ar
INNER JOIN resources r ON r.id = ar.resource_id
INNER JOIN systems s ON s.id = r.system_id
WHERE
    ($1::text = '' OR ar.name ILIKE '%' || $1 || '%' OR COALESCE(ar.description, '') ILIKE '%' || $1 || '%')
    AND ($2::uuid IS NULL OR s.id = $2::uuid)
    AND ($3::uuid IS NULL OR r.id = $3::uuid)
ORDER BY LOWER(ar.name)
LIMIT 5000
`

type SearchAccessRolesParams struct {
	SearchQ          string      `json:"search_q"`
	FilterSystemID   pgtype.UUID `json:"filter_system_id"`
	FilterResourceID pgtype.UUID `json:"filter_resource_id"`
}

type SearchAccessRolesRow struct {
	AccessRoleID      pgtype.UUID `json:"access_role_id"`
	ResourceID        pgtype.UUID `json:"resource_id"`
	RoleName          string      `json:"role_name"`
	RoleDescription   pgtype.Text `json:"role_description"`
	RiskLevel         string      `json:"risk_level"`
	ResourceName      string      `json:"resource_name"`
	ResourceSensitive bool        `json:"resource_sensitive"`
	SystemID          pgtype.UUID `json:"system_id"`
	SystemName        string      `json:"system_name"`
}

func (q *Queries) SearchAccessRoles(ctx context.Context, arg SearchAccessRolesParams) ([]SearchAccessRolesRow, error) {
	rows, err := q.db.Query(ctx, searchAccessRoles, arg.SearchQ, arg.FilterSystemID, arg.FilterResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAccessRolesRow{}
	for rows.Next() {
		var i SearchAccessRolesRow
		if err := rows.Scan(
			&i.AccessRoleID,
			&i.ResourceID,
			&i.RoleName,
			&i.RoleDescription,
			&i.RiskLevel,
			&i.ResourceName,
			&i.ResourceSensitive,
			&i.SystemID,
			&i.SystemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
