// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessRole struct {
	ID          pgtype.UUID `json:"id"`
	ResourceID  pgtype.UUID `json:"resource_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	RiskLevel   string      `json:"risk_level"`
}

type AiDecision struct {
	ID             pgtype.UUID        `json:"id"`
	RequestID      pgtype.UUID        `json:"request_id"`
	Recommendation string             `json:"recommendation"`
	RiskScore      float64            `json:"risk_score"`
	Confidence     float64            `json:"confidence"`
	Reason         pgtype.Text        `json:"reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Approval struct {
	ID         pgtype.UUID        `json:"id"`
	RequestID  pgtype.UUID        `json:"request_id"`
	ApproverID pgtype.UUID        `json:"approver_id"`
	StepNumber int32              `json:"step_number"`
	Status     string             `json:"status"`
	DecisionAt pgtype.Timestamptz `json:"decision_at"`
	Comment    pgtype.Text        `json:"comment"`
}

type Attachment struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	RequestID    pgtype.UUID        `json:"request_id"`
	OriginalName string             `json:"original_name"`
	ContentType  string             `json:"content_type"`
	S3Key        string             `json:"s3_key"`
	SizeBytes    int64              `json:"size_bytes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	RequestID pgtype.UUID        `json:"request_id"`
	Action    string             `json:"action"`
	Details   []byte             `json:"details"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Delegation struct {
	ID         pgtype.UUID `json:"id"`
	FromUserID pgtype.UUID `json:"from_user_id"`
	ToUserID   pgtype.UUID `json:"to_user_id"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
	Permanent  bool        `json:"permanent"`
}

// DelegationListRow — список делегирований с ФИО и логинами сторон.
type DelegationListRow struct {
	ID              pgtype.UUID `json:"id"`
	FromUserID      pgtype.UUID `json:"from_user_id"`
	ToUserID        pgtype.UUID `json:"to_user_id"`
	StartDate       pgtype.Date `json:"start_date"`
	EndDate         pgtype.Date `json:"end_date"`
	Permanent       bool        `json:"permanent"`
	FromLogin       string      `json:"from_login"`
	FromFullName    string      `json:"from_full_name"`
	ToLogin         string      `json:"to_login"`
	ToFullName      string      `json:"to_full_name"`
	AccessRolesJSON string      `json:"access_roles_json"`
}

// ApproverAccessRoleRow — роль доступа из каталога, где пользователь указан в цепочке согласования.
type ApproverAccessRoleRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

type Department struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

type RbacRole struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

type Request struct {
	ID            pgtype.UUID        `json:"id"`
	InitiatorID   pgtype.UUID        `json:"initiator_id"`
	Status        string             `json:"status"`
	RiskScore     pgtype.Float8      `json:"risk_score"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Justification pgtype.Text        `json:"justification"`
	NeededUntil   pgtype.Date        `json:"needed_until"`
}

type RequestItem struct {
	ID           pgtype.UUID `json:"id"`
	RequestID    pgtype.UUID `json:"request_id"`
	AccessRoleID pgtype.UUID `json:"access_role_id"`
}

type Resource struct {
	ID          pgtype.UUID `json:"id"`
	SystemID    pgtype.UUID `json:"system_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	Sensitive   bool        `json:"sensitive"`
}

type System struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Login        string             `json:"login"`
	FullName     string             `json:"full_name"`
	Email        string             `json:"email"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	Position     string             `json:"position"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PasswordHash pgtype.Text        `json:"password_hash"`
}

type UserRole struct {
	UserID     pgtype.UUID `json:"user_id"`
	RbacRoleID pgtype.UUID `json:"rbac_role_id"`
}
