// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: requests.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRequestByID = `-- name: GetRequestByID :one
SELECT id, initiator_id, status, risk_score, created_at, updated_at, justification, needed_until
FROM requests
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetRequestByID(ctx context.Context, id pgtype.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.InitiatorID,
		&i.Status,
		&i.RiskScore,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Justification,
		&i.NeededUntil,
	)
	return i, err
}

const insertRequest = `-- name: InsertRequest :one
INSERT INTO requests (initiator_id, status, justification, risk_score, needed_until)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, initiator_id, status, risk_score, created_at, updated_at, justification, needed_until
`

type InsertRequestParams struct {
	InitiatorID   pgtype.UUID   `json:"initiator_id"`
	Status        string        `json:"status"`
	Justification pgtype.Text   `json:"justification"`
	RiskScore     pgtype.Float8 `json:"risk_score"`
	NeededUntil   pgtype.Date   `json:"needed_until"`
}

func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, insertRequest,
		arg.InitiatorID,
		arg.Status,
		arg.Justification,
		arg.RiskScore,
		arg.NeededUntil,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.InitiatorID,
		&i.Status,
		&i.RiskScore,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Justification,
		&i.NeededUntil,
	)
	return i, err
}

const insertRequestItem = `-- name: InsertRequestItem :exec
INSERT INTO request_items (id, request_id, access_role_id, justification)
VALUES ($1, $2, $3, $4)
`

type InsertRequestItemParams struct {
	ID            pgtype.UUID `json:"id"`
	RequestID     pgtype.UUID `json:"request_id"`
	AccessRoleID  pgtype.UUID `json:"access_role_id"`
	Justification pgtype.Text `json:"justification"`
}

func (q *Queries) InsertRequestItem(ctx context.Context, arg InsertRequestItemParams) error {
	_, err := q.db.Exec(ctx, insertRequestItem, arg.ID, arg.RequestID, arg.AccessRoleID, arg.Justification)
	return err
}

const listRequestItems = `-- name: ListRequestItems :many
SELECT ri.id, ri.request_id, ri.access_role_id, ar.name AS access_role_name, ar.risk_level, r.name AS resource_name, ri.justification
FROM request_items ri
INNER JOIN access_roles ar ON ar.id = ri.access_role_id
INNER JOIN resources r ON r.id = ar.resource_id
WHERE ri.request_id = $1
`

type ListRequestItemsRow struct {
	ID             pgtype.UUID `json:"id"`
	RequestID      pgtype.UUID `json:"request_id"`
	AccessRoleID   pgtype.UUID `json:"access_role_id"`
	AccessRoleName string      `json:"access_role_name"`
	RiskLevel      string      `json:"risk_level"`
	ResourceName   string      `json:"resource_name"`
	Justification  pgtype.Text `json:"justification"`
}

func (q *Queries) ListRequestItems(ctx context.Context, requestID pgtype.UUID) ([]ListRequestItemsRow, error) {
	rows, err := q.db.Query(ctx, listRequestItems, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestItemsRow{}
	for rows.Next() {
		var i ListRequestItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.AccessRoleID,
			&i.AccessRoleName,
			&i.RiskLevel,
			&i.ResourceName,
			&i.Justification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByInitiator = `-- name: ListRequestsByInitiator :many
SELECT
  r.id,
  r.initiator_id,
  r.status,
  r.risk_score,
  r.created_at,
  r.updated_at,
  r.justification,
  r.needed_until,
  COALESCE((
    SELECT string_agg(subq.role_name, ', ' ORDER BY subq.role_name)
    FROM (
      SELECT DISTINCT ar2.name AS role_name
      FROM request_items ri2
      INNER JOIN access_roles ar2 ON ar2.id = ri2.access_role_id
      WHERE ri2.request_id = r.id
    ) AS subq
  ), '')::text AS access_role_names,
  COALESCE((
    SELECT COUNT(*)::int FROM approvals ap WHERE ap.request_id = r.id
  ), 0) AS approvals_total,
  COALESCE((
    SELECT COUNT(*)::int FROM approvals ap WHERE ap.request_id = r.id AND ap.status = 'approved'
  ), 0) AS approvals_done,
  COALESCE(iu.full_name, '')::text AS initiator_full_name,
  COALESCE(iu.login, '')::text AS initiator_login
FROM requests r
INNER JOIN users iu ON iu.id = r.initiator_id
WHERE r.initiator_id = $1
ORDER BY r.created_at DESC
`

// RequestListRow — заявка в списке инициатора с названиями ролей доступа из позиций.
type RequestListRow struct {
	ID                 pgtype.UUID        `json:"id"`
	InitiatorID        pgtype.UUID        `json:"initiator_id"`
	Status             string             `json:"status"`
	RiskScore          pgtype.Float8      `json:"risk_score"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Justification      pgtype.Text        `json:"justification"`
	NeededUntil        pgtype.Date        `json:"needed_until"`
	AccessRoleNames    string             `json:"access_role_names"`
	ApprovalsTotal     int32              `json:"approvals_total"`
	ApprovalsDone      int32              `json:"approvals_done"`
	InitiatorFullName  string             `json:"initiator_full_name"`
	InitiatorLogin     string             `json:"initiator_login"`
}

func (q *Queries) ListRequestsByInitiator(ctx context.Context, initiatorID pgtype.UUID) ([]RequestListRow, error) {
	rows, err := q.db.Query(ctx, listRequestsByInitiator, initiatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RequestListRow{}
	for rows.Next() {
		var i RequestListRow
		if err := rows.Scan(
			&i.ID,
			&i.InitiatorID,
			&i.Status,
			&i.RiskScore,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Justification,
			&i.NeededUntil,
			&i.AccessRoleNames,
			&i.ApprovalsTotal,
			&i.ApprovalsDone,
			&i.InitiatorFullName,
			&i.InitiatorLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequestRisk = `-- name: UpdateRequestRisk :exec
UPDATE requests
SET risk_score = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateRequestRiskParams struct {
	ID        pgtype.UUID   `json:"id"`
	RiskScore pgtype.Float8 `json:"risk_score"`
}

func (q *Queries) UpdateRequestRisk(ctx context.Context, arg UpdateRequestRiskParams) error {
	_, err := q.db.Exec(ctx, updateRequestRisk, arg.ID, arg.RiskScore)
	return err
}

const updateRequestStatus = `-- name: UpdateRequestStatus :exec
UPDATE requests
SET status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateRequestStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateRequestStatus, arg.ID, arg.Status)
	return err
}
