// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, login, full_name, email, department_id, position, is_active, created_at, password_hash
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.FullName,
		&i.Email,
		&i.DepartmentID,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByIDForIAM = `-- name: GetUserByIDForIAM :one
SELECT u.id, u.login, u.full_name, u.email, u.position, u.is_active, d.name AS department_name
FROM users u
LEFT JOIN departments d ON d.id = u.department_id
WHERE u.id = $1
LIMIT 1
`

type GetUserByIDForIAMRow struct {
	ID             pgtype.UUID `json:"id"`
	Login          string      `json:"login"`
	FullName       string      `json:"full_name"`
	Email          string      `json:"email"`
	Position       string      `json:"position"`
	IsActive       bool        `json:"is_active"`
	DepartmentName pgtype.Text `json:"department_name"`
}

func (q *Queries) GetUserByIDForIAM(ctx context.Context, id pgtype.UUID) (GetUserByIDForIAMRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDForIAM, id)
	var i GetUserByIDForIAMRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.FullName,
		&i.Email,
		&i.Position,
		&i.IsActive,
		&i.DepartmentName,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, full_name, email, department_id, position, is_active, created_at, password_hash
FROM users
WHERE login = $1
LIMIT 1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.FullName,
		&i.Email,
		&i.DepartmentID,
		&i.Position,
		&i.IsActive,
		&i.CreatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const listRbacNamesForUser = `-- name: ListRbacNamesForUser :many
SELECT r.name
FROM rbac_roles r
INNER JOIN user_roles ur ON ur.rbac_role_id = r.id
WHERE ur.user_id = $1
ORDER BY r.name
`

func (q *Queries) ListRbacNamesForUser(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRbacNamesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
